### PR TITLE
Combine docstrings

### LINKED ISSUE #8: Collect docstring from registered functions
Hi! I just found this library and really like it so far, but I miss having the docstring available in the tooltip when calling a multimethod in a Jupyter Notebook.

### PR DESCRIPTION
**Pull request by bagibence**
I copied the approach from the [multipledispatch](https://github.com/mrocklin/multipledispatch) library and quickly threw together an example of how the docstrings from the registered functions of a multimethod could be combined.

I'm not sure if this is the right approach here or if it messes up anything else, just thought it might be useful.

Fixes #8

### CODE REVIEW

**Comment by coady** [comment]
The build failure is because f-strings were added in 3.6.  Maybe it's time to drop 3.5 support anyway; many projects have already.

**Comment by bagibence** [comment]
Or do you want me to rewrite it and use another way of formatting?

**Comment by coady** [comment]
I'm not sure separating the doc/no-doc into 2 groups is necessary vs just leaving an empty string, so I might make that edit.  Thanks for the contribution!

**Comment by coady** [comment]
> This is a little bit (very) ugly: https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.misc.inner_product.html#skfda.misc.inner_product
> 
> Can it be made opt-in at least?

Looks like in that example only in the first function has a docstring. Would it work for your use case to ignore functions without a docstring?

**Comment by vnmabus** [comment]
I think so, yes.

**Comment by vnmabus** [comment]
When will this change be released?

**Comment by coady** [comment]
> When will this change be released?

Released [v1.7](https://github.com/coady/multimethod/releases/tag/v1.7).

**Comment by vnmabus** [comment]
Thank you!

**Pull request merged**
